/**
 * Curated Evidence Library — versioned, peer-reviewed, human-reviewed.
 *
 * Nothing in here is generated by a model and nothing is scraped from the web.
 * Each record is a small, auditable unit of clinical evidence with explicit
 * applicability criteria, so the Evidence Engine can decide whether it fits a
 * particular person without knowing anything about the science itself.
 *
 * Adding evidence is additive: append a record, bump LIBRARY_VERSION. The
 * engine architecture never changes.
 */
import type { EvidenceQuality, EvidenceStatus, RecommendationStrength } from "@/lib/evidence-types";

export const LIBRARY_VERSION = "2026.07.1";

/** The facts about a person the library is allowed to look at. */
export type EvidenceSubject = {
  lifeStage: string | null;
  cyclePhase: string | null;
  cycleDay: number | null;
  goals: string[];
  medications: string[];
  /** Latest values, by category. */
  latest: Record<string, string>;
  /** Every category ever shared. */
  categories: string[];
  /** Keys of beliefs that are currently holding up. */
  beliefsHolding: string[];
  symptoms: string[];
  flowHeavy: boolean;
  observationCount: number;
  /** 0–100 understanding depth. */
  depth: number;
};

export type EvidenceRecord = {
  id: string;
  version: string;
  status: EvidenceStatus;
  /** Clinical domain, e.g. Menstrual health, Sleep, Perimenopause. */
  domain: string;
  /** Population the evidence was established in. */
  population: string[];
  intervention: string;
  expectedOutcome: string;
  evidenceQuality: EvidenceQuality;
  recommendationStrength: RecommendationStrength;
  citations: string[];
  /** ISO date this record was last reviewed by a human. */
  dateReviewed: string;
  /** Plain-language description of who this applies to. */
  applicabilityCriteria: string;
  /**
   * Applicability, 0–1. 0 means "does not apply to this person right now".
   * Only reads the subject; never reads raw observations.
   */
  applies: (subject: EvidenceSubject) => number;
  /** The user-facing shape of the recommendation, in Ciatta's voice. */
  guidance: { lead: string; rest: string; support: string };
};

const RECORDS: EvidenceRecord[] = [
  {
    id: "hmb-iron-awareness",
    version: "1.0.0",
    status: "active",
    domain: "Menstrual health",
    population: ["Menstruating adults", "Heavy menstrual bleeding"],
    intervention: "Recognise heavy bleeding days and plan protection and iron intake around them",
    expectedOutcome: "Fewer unmanaged heavy days and lower risk of iron deficiency",
    evidenceQuality: "high",
    recommendationStrength: "strong",
    citations: [
      "NICE NG88, Heavy menstrual bleeding: assessment and management (2018, updated 2021)",
      "ACOG Committee Opinion 785, Screening and management of bleeding disorders in adolescents with heavy menstrual bleeding",
    ],
    dateReviewed: "2026-06-01",
    applicabilityCriteria: "Someone who has told Ciatta their flow is currently heavy.",
    applies: (s) => (s.flowHeavy ? 0.92 : 0),
    guidance: {
      lead: "Stay ahead of it.",
      rest: "Heavier days usually mean changing sooner than usual, and iron-rich food helps more today than most days.",
      support:
        "Heavy days are the ones worth planning around — that's well established, not a guess.",
    },
  },
  {
    id: "sleep-regularity-recovery",
    version: "1.0.0",
    status: "active",
    domain: "Sleep",
    population: ["Adults", "Short or fragmented sleep"],
    intervention: "Protect an earlier, regular sleep window after a poor night",
    expectedOutcome: "Better next-day energy, mood and glucose regulation",
    evidenceQuality: "high",
    recommendationStrength: "strong",
    citations: [
      "AASM & SRS Consensus, Recommended amount of sleep for a healthy adult (Sleep, 2015)",
      "Chaput et al., Sleep timing, sleep consistency and health (Applied Physiology, 2020)",
    ],
    dateReviewed: "2026-06-01",
    applicabilityCriteria: "Someone whose most recent sleep was poor or broken.",
    applies: (s) => {
      const sleep = s.latest["Sleep"];
      if (sleep === "Barely slept") return 0.9;
      if (sleep === "Restless" || sleep === "Broken") return 0.75;
      return 0;
    },
    guidance: {
      lead: "Protect your rest.",
      rest: "An earlier, steadier night would do more for tomorrow than anything else you could change today.",
      support: "Sleep regularity is one of the most reliably useful things there is.",
    },
  },
  {
    id: "luteal-load-adjustment",
    version: "1.0.0",
    status: "active",
    domain: "Menstrual health",
    population: ["Menstruating adults", "Late luteal phase"],
    intervention:
      "Keep training load moderate in the late luteal phase and raise fluid and carbohydrate intake",
    expectedOutcome: "Steadier perceived effort and fewer symptom flares before bleeding starts",
    evidenceQuality: "moderate",
    recommendationStrength: "conditional",
    citations: [
      "McNulty et al., The effects of menstrual cycle phase on exercise performance (Sports Medicine, 2020)",
      "Elliott-Sale et al., Methodological considerations for studies in sport and exercise science with women (Sports Medicine, 2021)",
    ],
    dateReviewed: "2026-06-01",
    applicabilityCriteria:
      "Someone in the luteal phase who has shared enough cycle and symptom information to place them there.",
    applies: (s) => {
      if (s.cyclePhase !== "luteal") return 0;
      const base = 0.6;
      const withSymptoms = s.symptoms.length ? 0.15 : 0;
      const withBelief = s.beliefsHolding.includes("mood-before-period") ? 0.15 : 0;
      return base + withSymptoms + withBelief;
    },
    guidance: {
      lead: "Ease the load a little.",
      rest: "This part of your cycle usually asks for slightly less intensity and a bit more food and water than you'd expect.",
      support: "Effort tends to feel harder here for reasons that have nothing to do with fitness.",
    },
  },
  {
    id: "dysmenorrhoea-heat-nsaid",
    version: "1.0.0",
    status: "active",
    domain: "Menstrual health",
    population: ["Menstruating adults", "Primary dysmenorrhoea"],
    intervention: "Apply local heat and use timely analgesia at the start of cramping",
    expectedOutcome: "Meaningful reduction in period pain intensity",
    evidenceQuality: "high",
    recommendationStrength: "strong",
    citations: [
      "Marjoribanks et al., NSAIDs for dysmenorrhoea (Cochrane Database of Systematic Reviews, 2015)",
      "Jo & Lee, Heat therapy for primary dysmenorrhea (Scientific Reports, 2018)",
    ],
    dateReviewed: "2026-06-01",
    applicabilityCriteria: "Someone reporting cramps or pelvic pain during the menstrual phase.",
    applies: (s) => {
      const cramping = s.symptoms.some((v) => /cramp|pain/i.test(v));
      if (!cramping) return 0;
      return s.cyclePhase === "menstrual" ? 0.88 : 0.7;
    },
    guidance: {
      lead: "Treat the pain early.",
      rest: "Heat and taking something at the first sign — rather than waiting it out — works far better than catching up later.",
      support: "This is one of the few things with genuinely strong evidence behind it.",
    },
  },
  {
    id: "perimenopause-strength-sleep",
    version: "1.0.0",
    status: "active",
    domain: "Perimenopause",
    population: ["Perimenopausal adults", "Menopausal transition"],
    intervention: "Regular resistance training plus a cool, consistent sleep environment",
    expectedOutcome: "Preserved bone and muscle, fewer night-time disruptions",
    evidenceQuality: "moderate",
    recommendationStrength: "conditional",
    citations: [
      "NICE NG23, Menopause: diagnosis and management (2015, updated 2019)",
      "Kanaley et al., Exercise/physical activity in individuals with type 2 diabetes and midlife women (ACSM, 2022)",
    ],
    dateReviewed: "2026-06-01",
    applicabilityCriteria:
      "Someone who has told Ciatta they are perimenopausal or in the transition.",
    applies: (s) => {
      if (!s.lifeStage) return 0;
      return /peri|menopaus/i.test(s.lifeStage) ? 0.8 : 0;
    },
    guidance: {
      lead: "Keep the strength work.",
      rest: "Loading your muscles a couple of times a week, and keeping the room cool at night, matter more now than they used to.",
      support:
        "This is the part of the picture that holds up best across the research for this stage.",
    },
  },
  {
    id: "recovery-after-hard-effort",
    version: "1.0.0",
    status: "active",
    domain: "Recovery",
    population: ["Physically active adults"],
    intervention: "Follow a hard session with a genuinely easy day, protein and sleep",
    expectedOutcome: "Better adaptation and lower injury and illness risk",
    evidenceQuality: "moderate",
    recommendationStrength: "conditional",
    citations: [
      "Kellmann et al., Recovery and performance in sport: consensus statement (IJSPP, 2018)",
      "Bishop et al., Recovery from training: a brief review (JSCR, 2008)",
    ],
    dateReviewed: "2026-06-01",
    applicabilityCriteria: "Someone whose most recent activity was hard.",
    applies: (s) => (s.latest["Activity"] === "Hard" ? 0.7 : 0),
    guidance: {
      lead: "Make today the easy one.",
      rest: "After a hard session, the adaptation happens in the recovery — food, sleep and a genuinely light day.",
      support: "Easy days are what make hard days work.",
    },
  },
];

export function libraryRecords(): EvidenceRecord[] {
  return RECORDS.filter((r) => r.status === "active");
}

export function libraryStats() {
  return {
    version: LIBRARY_VERSION,
    active: RECORDS.filter((r) => r.status === "active").length,
    total: RECORDS.length,
  };
}
