/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedTeachRouteImport } from './routes/_authenticated/teach'
import { Route as AuthenticatedTalkRouteImport } from './routes/_authenticated/talk'
import { Route as AuthenticatedQuickAddRouteImport } from './routes/_authenticated/quick-add'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedFirstObservationRouteImport } from './routes/_authenticated/first-observation'
import { Route as AuthenticatedEngineTraceRouteImport } from './routes/_authenticated/engine-trace'
import { Route as AuthenticatedCaptureRouteImport } from './routes/_authenticated/capture'
import { Route as AuthenticatedAttachRouteImport } from './routes/_authenticated/attach'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as AuthenticatedProfileSettingsSectionRouteImport } from './routes/_authenticated/profile.settings.$section'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeachRoute = AuthenticatedTeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalkRoute = AuthenticatedTalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickAddRoute = AuthenticatedQuickAddRouteImport.update({
  id: '/quick-add',
  path: '/quick-add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirstObservationRoute =
  AuthenticatedFirstObservationRouteImport.update({
    id: '/first-observation',
    path: '/first-observation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEngineTraceRoute =
  AuthenticatedEngineTraceRouteImport.update({
    id: '/engine-trace',
    path: '/engine-trace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaptureRoute = AuthenticatedCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttachRoute = AuthenticatedAttachRouteImport.update({
  id: '/attach',
  path: '/attach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileSettingsSectionRoute =
  AuthenticatedProfileSettingsSectionRouteImport.update({
    id: '/profile/settings/$section',
    path: '/profile/settings/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/attach': typeof AuthenticatedAttachRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/engine-trace': typeof AuthenticatedEngineTraceRoute
  '/first-observation': typeof AuthenticatedFirstObservationRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/quick-add': typeof AuthenticatedQuickAddRoute
  '/talk': typeof AuthenticatedTalkRoute
  '/teach': typeof AuthenticatedTeachRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/profile/settings/$section': typeof AuthenticatedProfileSettingsSectionRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/attach': typeof AuthenticatedAttachRoute
  '/capture': typeof AuthenticatedCaptureRoute
  '/engine-trace': typeof AuthenticatedEngineTraceRoute
  '/first-observation': typeof AuthenticatedFirstObservationRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/quick-add': typeof AuthenticatedQuickAddRoute
  '/talk': typeof AuthenticatedTalkRoute
  '/teach': typeof AuthenticatedTeachRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/': typeof AuthenticatedIndexRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/profile/settings/$section': typeof AuthenticatedProfileSettingsSectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/attach': typeof AuthenticatedAttachRoute
  '/_authenticated/capture': typeof AuthenticatedCaptureRoute
  '/_authenticated/engine-trace': typeof AuthenticatedEngineTraceRoute
  '/_authenticated/first-observation': typeof AuthenticatedFirstObservationRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/quick-add': typeof AuthenticatedQuickAddRoute
  '/_authenticated/talk': typeof AuthenticatedTalkRoute
  '/_authenticated/teach': typeof AuthenticatedTeachRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/profile/settings/$section': typeof AuthenticatedProfileSettingsSectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/attach'
    | '/capture'
    | '/engine-trace'
    | '/first-observation'
    | '/journey'
    | '/onboarding'
    | '/quick-add'
    | '/talk'
    | '/teach'
    | '/api/transcribe'
    | '/profile/edit'
    | '/profile/'
    | '/profile/settings/$section'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/attach'
    | '/capture'
    | '/engine-trace'
    | '/first-observation'
    | '/journey'
    | '/onboarding'
    | '/quick-add'
    | '/talk'
    | '/teach'
    | '/api/transcribe'
    | '/'
    | '/profile/edit'
    | '/profile'
    | '/profile/settings/$section'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/_authenticated/attach'
    | '/_authenticated/capture'
    | '/_authenticated/engine-trace'
    | '/_authenticated/first-observation'
    | '/_authenticated/journey'
    | '/_authenticated/onboarding'
    | '/_authenticated/quick-add'
    | '/_authenticated/talk'
    | '/_authenticated/teach'
    | '/api/transcribe'
    | '/_authenticated/'
    | '/_authenticated/profile/edit'
    | '/_authenticated/profile/'
    | '/_authenticated/profile/settings/$section'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teach': {
      id: '/_authenticated/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof AuthenticatedTeachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talk': {
      id: '/_authenticated/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof AuthenticatedTalkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quick-add': {
      id: '/_authenticated/quick-add'
      path: '/quick-add'
      fullPath: '/quick-add'
      preLoaderRoute: typeof AuthenticatedQuickAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/first-observation': {
      id: '/_authenticated/first-observation'
      path: '/first-observation'
      fullPath: '/first-observation'
      preLoaderRoute: typeof AuthenticatedFirstObservationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engine-trace': {
      id: '/_authenticated/engine-trace'
      path: '/engine-trace'
      fullPath: '/engine-trace'
      preLoaderRoute: typeof AuthenticatedEngineTraceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capture': {
      id: '/_authenticated/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AuthenticatedCaptureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attach': {
      id: '/_authenticated/attach'
      path: '/attach'
      fullPath: '/attach'
      preLoaderRoute: typeof AuthenticatedAttachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/settings/$section': {
      id: '/_authenticated/profile/settings/$section'
      path: '/profile/settings/$section'
      fullPath: '/profile/settings/$section'
      preLoaderRoute: typeof AuthenticatedProfileSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttachRoute: typeof AuthenticatedAttachRoute
  AuthenticatedCaptureRoute: typeof AuthenticatedCaptureRoute
  AuthenticatedEngineTraceRoute: typeof AuthenticatedEngineTraceRoute
  AuthenticatedFirstObservationRoute: typeof AuthenticatedFirstObservationRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedQuickAddRoute: typeof AuthenticatedQuickAddRoute
  AuthenticatedTalkRoute: typeof AuthenticatedTalkRoute
  AuthenticatedTeachRoute: typeof AuthenticatedTeachRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProfileSettingsSectionRoute: typeof AuthenticatedProfileSettingsSectionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttachRoute: AuthenticatedAttachRoute,
  AuthenticatedCaptureRoute: AuthenticatedCaptureRoute,
  AuthenticatedEngineTraceRoute: AuthenticatedEngineTraceRoute,
  AuthenticatedFirstObservationRoute: AuthenticatedFirstObservationRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedQuickAddRoute: AuthenticatedQuickAddRoute,
  AuthenticatedTalkRoute: AuthenticatedTalkRoute,
  AuthenticatedTeachRoute: AuthenticatedTeachRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProfileSettingsSectionRoute:
    AuthenticatedProfileSettingsSectionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
